<?php

/**
 * Created by PhpStorm.
 * User: 0375
 * Date: 2018/9/17
 * Time: 11:45
 */
namespace app\lib\exception;

use Exception;
use think\exception\Handle;

class ExceptionHandler extends Handle
{
    public function render(Exception $e)
    {
        return json('throw test');
        return parent::render($e); // TODO: Change the autogenerated stub
    }
}